### ISSUE TITLE
header.phtml 

### ISSUE THREAD

**Issue by EffectICT** [CyberfusionNL/HostFact-Verwerkersovereenkomst#13]
First off all thanks for sharing this.  In your readme file you write the following

You can use the following code in your custom/views/header.phtml to show a message to all debtors that haven't signed the DPA yet in the `klantenpaneel`. Below code will check if the debtor has agreed to the DPA yet, and if not, a message will be shown.

***Note*: this code is not working at the moment, because it relies on some variables only passed by HostFact in the `dpa` view. **Will try to fix...****

    <?php
    $dpa = new Dpa\Dpa_Model();

    if ($dpa->debtorDPAStatus() == '' && strpos($_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'], __('dpa', 'url', 'dpa')) == false) {
        echo '<div class="alert alert-warning" role="alert"><p>'.__('dpa not accepted').' <a href="/klantenpaneel/'.__('dpa', 'url', 'dpa').'/">'.__('accept').'</a></p></div>';
    }
    ?>-->

I am not a programmer but would really like to use this option when can we expect an update on this feature?

Thanks in advanced.

**Comment by YWatchman** [comment]
This will be available asap, I'd expect within now and 2 weeks. This is for us a very busy period.

**Comment by EffectICT** [comment]
Any update about this issue? TIA

**Comment by YWatchman** [comment]
I found the issue...

Include this in your header (custom/views/header.phtml)
```
require_once(CUSTOMPATH . '/plugins/dpa/config.php');
require_once(CUSTOMPATH . '/plugins/dpa/models/dpa_model.php');

$dpa = new \Dpa\Dpa_Model();
global $config;
```

Then where you'd like to have a alert something like
```
<?php if ($dpa->debtorDPAStatus($config)): ?>
<div class="box box-warning">
    Your content
</div>
<?php endif; ?>
```

and modify the dpa_model.php (custom/plugins/dpa/models/) function debtorDPAStatus:
```
    /**
     * Retrieve debtor DPA info.
     * Hotfix by YWatchman <YWatchman@cyberfusion.nl>
     * 
     * @return string
     */
    public function debtorDPAStatus($config = null)
    {
        $debtor = $this->getCurrentDebtor();
        $response = $this->APIRequest('debtor', 'show', array('Identifier' => $debtor));

        $this->config = $config != null ? $config : $this->config;

        // If custom field is filled, debtor agreed already
        if ( isset($response['debtor']['CustomFields'][$this->config['fieldname']]) && $response['debtor']['CustomFields'][$this->config['fieldname']] != "" ) {
            return $response['debtor']['CustomFields'][$this->config['fieldname']];
        } else {
            return '';
        }
    }
```

I will make a pull request for my colleague.

**Comment by YWatchman** [comment]
Oh I forgot to mention a single thing in the config.php (custom/plugins/dpa/) you will have to prepend one line.
```
global $config;
````

**Comment by WilliamDEdwards** [comment]
Hotfix has been merged.

**Comment by EffectICT** [comment]
Thanks for the update and I have uploaded the new files and created the header.phtml with the "new" code but still i don't receive a message to all debtors that haven't signed the DPA yet in the `klantenpaneel`  How can I troubelshoot tis and make it work?

**Comment by YWatchman** [comment]
I can't help you without your current code, please supply us with a snippet.
