### ISSUE TITLE
Geen datum/ip adres na ondertekening en niet onthouden

### ISSUE THREAD

**Issue by jeroenedig** [CyberfusionNL/HostFact-Verwerkersovereenkomst#4]
Na het onderteken wordt er geen data en overige info weergegeven. Zie: https://ibb.co/dG5Jfo

Ook als de klant daarna weer op 'verwerkersovereenkomst' klikt moet hij/zij deze wederom accepteren (akkoord wordt niet (goed) opgeslagen)

**Comment by WilliamDEdwards** [comment]
Dan staat je veldcode niet goed in `config.php`. Dat moet de veldcode zijn. Geen ID en ook niet de naam.

**Comment by WilliamDEdwards** [comment]
FYI, het probleem was het vinkje bij 'Gebruiken bij': daar moest 'Debiteur' nog geselecteerd worden. Heb ik ook toegevoegd aan de README.
